//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebook2memrise.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_raw
    {
        public int Id { get; set; }
        public string file_name { get; set; }
        public byte[] file_content { get; set; }
    }
}
